## Basic Configuration

baseurl = "https://eztechconsultants.com"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "EZ Tech Consultants"
title = "EZ Tech Consultants"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "EZ Tech Consultants"
intro = "[info@eztechconsultants.com](info@eztechconsultants.com)"
description = "Computers | Mobile Devices | Office 365 | Google Workspace | <br/> Okta | Jamf | Intune"
authorimage = ""
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "EZ Tech Consultants"
keywords = "msp,intune,jamf,dlp,o365,okta,google,workspace,azure"

## Social Accounts
[params.social]
#github = "<username>"
#instagram = "<username>"
#xing = "<username>"
#linkedin = "<username>"
#twitter = "<username>"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
#orcid = "0123-4567-8901-2345"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
#buymeacoffee = "<username>"
#kaggle = "<username>"
email = "info@eztechconsultants.com"
#pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2023. EZ Tech Consultants. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
#[[menu.main]]
#    name = "blog"
#    weight = 100
#    identifier = "blog"
#    url = "/blog/"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
